CREATE TABLE pokemon (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  pokemonName VARCHAR(255) NOT NULL,
  pokemonUrl VARCHAR(255) NOT NULL,
  experience INT NOT NULL,
  heigth INT NOT NULL,
  hp INT NOT NULL,
  attack INT NOT NULL,
  defense INT NOT NULL,
  specialAttack INT NOT NULL,
  specialDefense INT NOT NULL,
  speed INT NOT NULL,
  pokemonWeight INT NOT NULL,
  primaryType VARCHAR(255) NOT NULL,
  secondaryType VARCHAR(255) NULL,
  pokemonPrice INT NOT NULL,
  firstAbility VARCHAR(255) NOT NULL,
  secondAbility VARCHAR(255),
  firstMove VARCHAR(255) NOT NULL,
  secondMove VARCHAR(255) NOT NULL,
  thirdMove VARCHAR(255) NOT NULL,
  fourthMove VARCHAR(255) NOT NULL
) 
ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO pokemon(id,pokemonName,pokemonUrl,experience,heigth,hp,attack,defense,specialAttack,specialDefense,speed,pokemonWeight,primaryType,secondaryType,pokemonPrice,firstAbility,secondAbility,firstMove,secondMove,thirdMove,fourthMove) VALUES (1,'bulbasaur','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/1.svg',64,7,45,49,49,65,65,45,69,'grass','poison',10,'overgrow','chlorophyll','razor-wind','swords-dance','cut','bind');
INSERT INTO pokemon(id,pokemonName,pokemonUrl,experience,heigth,hp,attack,defense,specialAttack,specialDefense,speed,pokemonWeight,primaryType,secondaryType,pokemonPrice,firstAbility,secondAbility,firstMove,secondMove,thirdMove,fourthMove) VALUES (2,'ivysaur','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/2.svg',142,10,60,62,63,80,80,60,130,'grass','poison',22,'overgrow','chlorophyll','swords-dance','cut','bind','vine-whip');
INSERT INTO pokemon(id,pokemonName,pokemonUrl,experience,heigth,hp,attack,defense,specialAttack,specialDefense,speed,pokemonWeight,primaryType,secondaryType,pokemonPrice,firstAbility,secondAbility,firstMove,secondMove,thirdMove,fourthMove) VALUES (3,'venusaur','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/3.svg',263,20,80,82,83,100,100,80,1000,'grass','poison',41,'overgrow','chlorophyll','swords-dance','cut','bind','vine-whip');
INSERT INTO pokemon(id,pokemonName,pokemonUrl,experience,heigth,hp,attack,defense,specialAttack,specialDefense,speed,pokemonWeight,primaryType,secondaryType,pokemonPrice,firstAbility,secondAbility,firstMove,secondMove,thirdMove,fourthMove) VALUES (4,'charmander','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/4.svg',62,6,39,52,43,60,50,65,85,'fire',NULL,10,'blaze','solar-power','mega-punch','fire-punch','thunder-punch','scratch');
INSERT INTO pokemon(id,pokemonName,pokemonUrl,experience,heigth,hp,attack,defense,specialAttack,specialDefense,speed,pokemonWeight,primaryType,secondaryType,pokemonPrice,firstAbility,secondAbility,firstMove,secondMove,thirdMove,fourthMove) VALUES (5,'charmeleon','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/5.svg',142,11,58,64,58,80,65,80,190,'fire',NULL,22,'blaze','solar-power','mega-punch','fire-punch','thunder-punch','scratch');
INSERT INTO pokemon(id,pokemonName,pokemonUrl,experience,heigth,hp,attack,defense,specialAttack,specialDefense,speed,pokemonWeight,primaryType,secondaryType,pokemonPrice,firstAbility,secondAbility,firstMove,secondMove,thirdMove,fourthMove) VALUES (6,'charizard','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/6.svg',267,17,78,84,78,109,85,100,905,'fire','flying',42,'blaze','solar-power','mega-punch','fire-punch','thunder-punch','scratch');
INSERT INTO pokemon(id,pokemonName,pokemonUrl,experience,heigth,hp,attack,defense,specialAttack,specialDefense,speed,pokemonWeight,primaryType,secondaryType,pokemonPrice,firstAbility,secondAbility,firstMove,secondMove,thirdMove,fourthMove) VALUES (7,'squirtle','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/7.svg',63,5,44,48,65,50,64,43,90,'water',NULL,10,'torrent','rain-dish','mega-punch','ice-punch','mega-kick','headbutt');
INSERT INTO pokemon(id,pokemonName,pokemonUrl,experience,heigth,hp,attack,defense,specialAttack,specialDefense,speed,pokemonWeight,primaryType,secondaryType,pokemonPrice,firstAbility,secondAbility,firstMove,secondMove,thirdMove,fourthMove) VALUES (8,'wartortle','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/8.svg',142,10,59,63,80,65,80,58,225,'water',NULL,22,'torrent','rain-dish','mega-punch','ice-punch','mega-kick','headbutt');
INSERT INTO pokemon(id,pokemonName,pokemonUrl,experience,heigth,hp,attack,defense,specialAttack,specialDefense,speed,pokemonWeight,primaryType,secondaryType,pokemonPrice,firstAbility,secondAbility,firstMove,secondMove,thirdMove,fourthMove) VALUES (9,'blastoise','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/9.svg',265,16,79,83,100,85,105,78,855,'water',NULL,41,'torrent','rain-dish','mega-punch','ice-punch','mega-kick','headbutt');
INSERT INTO pokemon(id,pokemonName,pokemonUrl,experience,heigth,hp,attack,defense,specialAttack,specialDefense,speed,pokemonWeight,primaryType,secondaryType,pokemonPrice,firstAbility,secondAbility,firstMove,secondMove,thirdMove,fourthMove) VALUES (10,'caterpie','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/10.svg',39,3,45,30,35,20,20,45,29,'bug',NULL,6,'shield-dust','run-away','tackle','string-shot','snore','bug-bite');
INSERT INTO pokemon(id,pokemonName,pokemonUrl,experience,heigth,hp,attack,defense,specialAttack,specialDefense,speed,pokemonWeight,primaryType,secondaryType,pokemonPrice,firstAbility,secondAbility,firstMove,secondMove,thirdMove,fourthMove) VALUES (11,'metapod','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/11.svg',72,7,50,20,55,25,25,30,99,'bug',NULL,11,'shed-skin',NULL,'string-shot','harden','iron-defense','bug-bite');
INSERT INTO pokemon(id,pokemonName,pokemonUrl,experience,heigth,hp,attack,defense,specialAttack,specialDefense,speed,pokemonWeight,primaryType,secondaryType,pokemonPrice,firstAbility,secondAbility,firstMove,secondMove,thirdMove,fourthMove) VALUES (12,'butterfree','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/12.svg',198,11,60,45,50,90,80,70,320,'bug','flying',31,'compound-eyes','tinted-lens','razor-wind','gust','whirlwind','headbutt');
INSERT INTO pokemon(id,pokemonName,pokemonUrl,experience,heigth,hp,attack,defense,specialAttack,specialDefense,speed,pokemonWeight,primaryType,secondaryType,pokemonPrice,firstAbility,secondAbility,firstMove,secondMove,thirdMove,fourthMove) VALUES (13,'weedle','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/13.svg',39,3,40,35,30,20,20,50,32,'bug','poison',6,'shield-dust','run-away','poison-sting','string-shot','bug-bite','electroweb');
INSERT INTO pokemon(id,pokemonName,pokemonUrl,experience,heigth,hp,attack,defense,specialAttack,specialDefense,speed,pokemonWeight,primaryType,secondaryType,pokemonPrice,firstAbility,secondAbility,firstMove,secondMove,thirdMove,fourthMove) VALUES (14,'kakuna','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/14.svg',72,6,45,25,50,25,25,35,100,'bug','poison',11,'shed-skin',NULL,'string-shot','harden','iron-defense','bug-bite');
INSERT INTO pokemon(id,pokemonName,pokemonUrl,experience,heigth,hp,attack,defense,specialAttack,specialDefense,speed,pokemonWeight,primaryType,secondaryType,pokemonPrice,firstAbility,secondAbility,firstMove,secondMove,thirdMove,fourthMove) VALUES (15,'beedrill','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/15.svg',178,10,65,90,40,45,80,75,295,'bug','poison',28,'swarm','sniper','swords-dance','cut','headbutt','fury-attack');
INSERT INTO pokemon(id,pokemonName,pokemonUrl,experience,heigth,hp,attack,defense,specialAttack,specialDefense,speed,pokemonWeight,primaryType,secondaryType,pokemonPrice,firstAbility,secondAbility,firstMove,secondMove,thirdMove,fourthMove) VALUES (16,'pidgey','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/16.svg',50,3,40,45,40,35,35,56,18,'normal','flying',8,'keen-eye','tangled-feet','razor-wind','gust','wing-attack','whirlwind');
INSERT INTO pokemon(id,pokemonName,pokemonUrl,experience,heigth,hp,attack,defense,specialAttack,specialDefense,speed,pokemonWeight,primaryType,secondaryType,pokemonPrice,firstAbility,secondAbility,firstMove,secondMove,thirdMove,fourthMove) VALUES (17,'pidgeotto','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/17.svg',122,11,63,60,55,50,50,71,300,'normal','flying',19,'keen-eye','tangled-feet','razor-wind','gust','wing-attack','whirlwind');
INSERT INTO pokemon(id,pokemonName,pokemonUrl,experience,heigth,hp,attack,defense,specialAttack,specialDefense,speed,pokemonWeight,primaryType,secondaryType,pokemonPrice,firstAbility,secondAbility,firstMove,secondMove,thirdMove,fourthMove) VALUES (18,'pidgeot','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/18.svg',216,15,83,80,75,70,70,101,395,'normal','flying',34,'keen-eye','tangled-feet','razor-wind','gust','wing-attack','whirlwind');
INSERT INTO pokemon(id,pokemonName,pokemonUrl,experience,heigth,hp,attack,defense,specialAttack,specialDefense,speed,pokemonWeight,primaryType,secondaryType,pokemonPrice,firstAbility,secondAbility,firstMove,secondMove,thirdMove,fourthMove) VALUES (19,'rattata','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/19.svg',51,3,30,56,35,25,35,72,35,'normal',NULL,8,'run-away','guts','cut','headbutt','tackle','body-slam');
INSERT INTO pokemon(id,pokemonName,pokemonUrl,experience,heigth,hp,attack,defense,specialAttack,specialDefense,speed,pokemonWeight,primaryType,secondaryType,pokemonPrice,firstAbility,secondAbility,firstMove,secondMove,thirdMove,fourthMove) VALUES (20,'raticate','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/20.svg',145,7,55,81,60,50,70,97,185,'normal',NULL,23,'run-away','guts','swords-dance','cut','headbutt','tackle');
INSERT INTO pokemon(id,pokemonName,pokemonUrl,experience,heigth,hp,attack,defense,specialAttack,specialDefense,speed,pokemonWeight,primaryType,secondaryType,pokemonPrice,firstAbility,secondAbility,firstMove,secondMove,thirdMove,fourthMove) VALUES (21,'spearow','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/21.svg',52,3,40,60,30,31,31,70,20,'normal','flying',8,'keen-eye','sniper','razor-wind','whirlwind','fly','headbutt');
INSERT INTO pokemon(id,pokemonName,pokemonUrl,experience,heigth,hp,attack,defense,specialAttack,specialDefense,speed,pokemonWeight,primaryType,secondaryType,pokemonPrice,firstAbility,secondAbility,firstMove,secondMove,thirdMove,fourthMove) VALUES (22,'fearow','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/22.svg',155,12,65,90,65,61,61,100,380,'normal','flying',24,'keen-eye','sniper','razor-wind','whirlwind','fly','headbutt');
INSERT INTO pokemon(id,pokemonName,pokemonUrl,experience,heigth,hp,attack,defense,specialAttack,specialDefense,speed,pokemonWeight,primaryType,secondaryType,pokemonPrice,firstAbility,secondAbility,firstMove,secondMove,thirdMove,fourthMove) VALUES (23,'ekans','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/23.svg',58,20,35,60,44,40,54,55,69,'poison',NULL,9,'intimidate','shed-skin','bind','slam','headbutt','body-slam');
INSERT INTO pokemon(id,pokemonName,pokemonUrl,experience,heigth,hp,attack,defense,specialAttack,specialDefense,speed,pokemonWeight,primaryType,secondaryType,pokemonPrice,firstAbility,secondAbility,firstMove,secondMove,thirdMove,fourthMove) VALUES (24,'arbok','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/24.svg',157,35,60,95,69,65,79,80,650,'poison',NULL,25,'intimidate','shed-skin','bind','slam','headbutt','body-slam');
INSERT INTO pokemon(id,pokemonName,pokemonUrl,experience,heigth,hp,attack,defense,specialAttack,specialDefense,speed,pokemonWeight,primaryType,secondaryType,pokemonPrice,firstAbility,secondAbility,firstMove,secondMove,thirdMove,fourthMove) VALUES (25,'pikachu','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/25.svg',112,4,35,55,40,50,50,90,60,'electric',NULL,18,'static','lightning-rod','mega-punch','pay-day','thunder-punch','slam');
INSERT INTO pokemon(id,pokemonName,pokemonUrl,experience,heigth,hp,attack,defense,specialAttack,specialDefense,speed,pokemonWeight,primaryType,secondaryType,pokemonPrice,firstAbility,secondAbility,firstMove,secondMove,thirdMove,fourthMove) VALUES (26,'raichu','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/26.svg',243,8,60,90,55,90,80,110,300,'electric',NULL,38,'static','lightning-rod','mega-punch','pay-day','thunder-punch','slam');
INSERT INTO pokemon(id,pokemonName,pokemonUrl,experience,heigth,hp,attack,defense,specialAttack,specialDefense,speed,pokemonWeight,primaryType,secondaryType,pokemonPrice,firstAbility,secondAbility,firstMove,secondMove,thirdMove,fourthMove) VALUES (27,'sandshrew','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/27.svg',60,6,50,75,85,20,30,40,120,'ground',NULL,9,'sand-veil','sand-rush','scratch','swords-dance','cut','sand-attack');
INSERT INTO pokemon(id,pokemonName,pokemonUrl,experience,heigth,hp,attack,defense,specialAttack,specialDefense,speed,pokemonWeight,primaryType,secondaryType,pokemonPrice,firstAbility,secondAbility,firstMove,secondMove,thirdMove,fourthMove) VALUES (28,'sandslash','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/28.svg',158,10,75,100,110,45,55,65,295,'ground',NULL,25,'sand-veil','sand-rush','scratch','swords-dance','cut','sand-attack');
INSERT INTO pokemon(id,pokemonName,pokemonUrl,experience,heigth,hp,attack,defense,specialAttack,specialDefense,speed,pokemonWeight,primaryType,secondaryType,pokemonPrice,firstAbility,secondAbility,firstMove,secondMove,thirdMove,fourthMove) VALUES (29,'nidorino','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/29.svg',55,4,55,47,52,40,40,41,70,'poison',NULL,9,'poison-point','rivalry','scratch','cut','double-kick','headbutt');
INSERT INTO pokemon(id,pokemonName,pokemonUrl,experience,heigth,hp,attack,defense,specialAttack,specialDefense,speed,pokemonWeight,primaryType,secondaryType,pokemonPrice,firstAbility,secondAbility,firstMove,secondMove,thirdMove,fourthMove) VALUES (30,'nidorina','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/30.svg',128,8,70,62,67,55,55,56,200,'poison',NULL,20,'poison-point','rivalry','scratch','cut','double-kick','headbutt');
INSERT INTO pokemon(id,pokemonName,pokemonUrl,experience,heigth,hp,attack,defense,specialAttack,specialDefense,speed,pokemonWeight,primaryType,secondaryType,pokemonPrice,firstAbility,secondAbility,firstMove,secondMove,thirdMove,fourthMove) VALUES (31,'nidoqueen','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/31.svg',253,13,90,92,87,75,85,76,600,'poison','ground',40,'poison-point','rivalry','mega-punch','pay-day','fire-punch','ice-punch');
INSERT INTO pokemon(id,pokemonName,pokemonUrl,experience,heigth,hp,attack,defense,specialAttack,specialDefense,speed,pokemonWeight,primaryType,secondaryType,pokemonPrice,firstAbility,secondAbility,firstMove,secondMove,thirdMove,fourthMove) VALUES (32,'nidoking','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/34.svg',253,14,81,102,77,85,75,85,620,'poison','ground',40,'poison-point','rivalry','mega-punch','pay-day','fire-punch','ice-punch');
INSERT INTO pokemon(id,pokemonName,pokemonUrl,experience,heigth,hp,attack,defense,specialAttack,specialDefense,speed,pokemonWeight,primaryType,secondaryType,pokemonPrice,firstAbility,secondAbility,firstMove,secondMove,thirdMove,fourthMove) VALUES (33,'clefairy','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/35.svg',113,6,70,45,48,60,65,35,75,'fairy',NULL,18,'cute-charm','magic-guard','pound','double-slap','mega-punch','fire-punch');
INSERT INTO pokemon(id,pokemonName,pokemonUrl,experience,heigth,hp,attack,defense,specialAttack,specialDefense,speed,pokemonWeight,primaryType,secondaryType,pokemonPrice,firstAbility,secondAbility,firstMove,secondMove,thirdMove,fourthMove) VALUES (34,'clefable','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/36.svg',242,13,95,70,73,95,90,60,400,'fairy',NULL,38,'cute-charm','magic-guard','pound','double-slap','mega-punch','fire-punch');
INSERT INTO pokemon(id,pokemonName,pokemonUrl,experience,heigth,hp,attack,defense,specialAttack,specialDefense,speed,pokemonWeight,primaryType,secondaryType,pokemonPrice,firstAbility,secondAbility,firstMove,secondMove,thirdMove,fourthMove) VALUES (35,'vulpix','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/37.svg',60,6,38,41,40,50,65,65,99,'fire',NULL,9,'flash-fire','drought','headbutt','tackle','body-slam','take-down');
INSERT INTO pokemon(id,pokemonName,pokemonUrl,experience,heigth,hp,attack,defense,specialAttack,specialDefense,speed,pokemonWeight,primaryType,secondaryType,pokemonPrice,firstAbility,secondAbility,firstMove,secondMove,thirdMove,fourthMove) VALUES (36,'ninetales','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/38.svg',177,11,73,76,75,81,100,100,199,'fire',NULL,28,'flash-fire','drought','headbutt','tackle','body-slam','take-down');
INSERT INTO pokemon(id,pokemonName,pokemonUrl,experience,heigth,hp,attack,defense,specialAttack,specialDefense,speed,pokemonWeight,primaryType,secondaryType,pokemonPrice,firstAbility,secondAbility,firstMove,secondMove,thirdMove,fourthMove) VALUES (37,'jigglypuff','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/39.svg',95,5,115,45,20,45,25,20,55,'normal','fairy',15,'cute-charm','competitive','pound','double-slap','mega-punch','fire-punch');
INSERT INTO pokemon(id,pokemonName,pokemonUrl,experience,heigth,hp,attack,defense,specialAttack,specialDefense,speed,pokemonWeight,primaryType,secondaryType,pokemonPrice,firstAbility,secondAbility,firstMove,secondMove,thirdMove,fourthMove) VALUES (38,'wigglytuff','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/40.svg',218,10,140,70,45,85,50,45,120,'normal','fairy',34,'cute-charm','competitive','pound','double-slap','mega-punch','fire-punch');
INSERT INTO pokemon(id,pokemonName,pokemonUrl,experience,heigth,hp,attack,defense,specialAttack,specialDefense,speed,pokemonWeight,primaryType,secondaryType,pokemonPrice,firstAbility,secondAbility,firstMove,secondMove,thirdMove,fourthMove) VALUES (39,'zubat','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/41.svg',49,8,40,45,35,30,40,55,75,'poison','flying',8,'inner-focus','infiltrator','razor-wind','gust','wing-attack','whirlwind');
INSERT INTO pokemon(id,pokemonName,pokemonUrl,experience,heigth,hp,attack,defense,specialAttack,specialDefense,speed,pokemonWeight,primaryType,secondaryType,pokemonPrice,firstAbility,secondAbility,firstMove,secondMove,thirdMove,fourthMove) VALUES (40,'golbat','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/42.svg',159,16,75,80,70,65,75,90,550,'poison','flying',25,'inner-focus','infiltrator','razor-wind','wing-attack','whirlwind','fly');
INSERT INTO pokemon(id,pokemonName,pokemonUrl,experience,heigth,hp,attack,defense,specialAttack,specialDefense,speed,pokemonWeight,primaryType,secondaryType,pokemonPrice,firstAbility,secondAbility,firstMove,secondMove,thirdMove,fourthMove) VALUES (41,'oddish','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/43.svg',64,5,45,50,55,75,65,30,54,'grass','poison',10,'chlorophyll','run-away','swords-dance','cut','headbutt','take-down');
INSERT INTO pokemon(id,pokemonName,pokemonUrl,experience,heigth,hp,attack,defense,specialAttack,specialDefense,speed,pokemonWeight,primaryType,secondaryType,pokemonPrice,firstAbility,secondAbility,firstMove,secondMove,thirdMove,fourthMove) VALUES (42,'gloom','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/44.svg',138,8,60,65,70,85,75,40,86,'grass','poison',22,'chlorophyll','stench','swords-dance','cut','headbutt','take-down');
INSERT INTO pokemon(id,pokemonName,pokemonUrl,experience,heigth,hp,attack,defense,specialAttack,specialDefense,speed,pokemonWeight,primaryType,secondaryType,pokemonPrice,firstAbility,secondAbility,firstMove,secondMove,thirdMove,fourthMove) VALUES (43,'vileplume','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/45.svg',245,12,75,80,85,110,90,50,186,'grass','poison',38,'chlorophyll','effect-spore','swords-dance','cut','headbutt','body-slam');
INSERT INTO pokemon(id,pokemonName,pokemonUrl,experience,heigth,hp,attack,defense,specialAttack,specialDefense,speed,pokemonWeight,primaryType,secondaryType,pokemonPrice,firstAbility,secondAbility,firstMove,secondMove,thirdMove,fourthMove) VALUES (44,'paras','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/46.svg',57,3,35,70,55,45,55,25,54,'bug','grass',9,'effect-spore','dry-skin','scratch','swords-dance','cut','headbutt');
INSERT INTO pokemon(id,pokemonName,pokemonUrl,experience,heigth,hp,attack,defense,specialAttack,specialDefense,speed,pokemonWeight,primaryType,secondaryType,pokemonPrice,firstAbility,secondAbility,firstMove,secondMove,thirdMove,fourthMove) VALUES (45,'parasect','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/47.svg',142,10,60,95,80,60,80,30,295,'bug','grass',22,'effect-spore','dry-skin','scratch','swords-dance','cut','headbutt');
INSERT INTO pokemon(id,pokemonName,pokemonUrl,experience,heigth,hp,attack,defense,specialAttack,specialDefense,speed,pokemonWeight,primaryType,secondaryType,pokemonPrice,firstAbility,secondAbility,firstMove,secondMove,thirdMove,fourthMove) VALUES (46,'venonat','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/48.svg',61,10,60,55,50,40,55,45,300,'bug','poison',10,'compound-eyes','tinted-lens','headbutt','tackle','take-down','double-edge');
INSERT INTO pokemon(id,pokemonName,pokemonUrl,experience,heigth,hp,attack,defense,specialAttack,specialDefense,speed,pokemonWeight,primaryType,secondaryType,pokemonPrice,firstAbility,secondAbility,firstMove,secondMove,thirdMove,fourthMove) VALUES (47,'venomoth','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/49.svg',158,15,70,65,60,90,75,90,125,'bug','poison',25,'shield-dust','tinted-lens','razor-wind','gust','whirlwind','headbutt');
INSERT INTO pokemon(id,pokemonName,pokemonUrl,experience,heigth,hp,attack,defense,specialAttack,specialDefense,speed,pokemonWeight,primaryType,secondaryType,pokemonPrice,firstAbility,secondAbility,firstMove,secondMove,thirdMove,fourthMove) VALUES (48,'diglett','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/50.svg',53,2,10,55,25,35,45,95,8,'ground',NULL,8,'sand-veil','arena-trap','scratch','cut','sand-attack','headbutt');
INSERT INTO pokemon(id,pokemonName,pokemonUrl,experience,heigth,hp,attack,defense,specialAttack,specialDefense,speed,pokemonWeight,primaryType,secondaryType,pokemonPrice,firstAbility,secondAbility,firstMove,secondMove,thirdMove,fourthMove) VALUES (49,'dugtrio','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/51.svg',149,7,35,100,50,50,70,120,333,'ground',NULL,23,'sand-veil','arena-trap','scratch','cut','sand-attack','headbutt');
INSERT INTO pokemon(id,pokemonName,pokemonUrl,experience,heigth,hp,attack,defense,specialAttack,specialDefense,speed,pokemonWeight,primaryType,secondaryType,pokemonPrice,firstAbility,secondAbility,firstMove,secondMove,thirdMove,fourthMove) VALUES (50,'meowth','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/52.svg',58,4,40,45,35,40,40,90,42,'normal',NULL,9,'pickup','technician','pay-day','scratch','cut','headbutt');
INSERT INTO pokemon(id,pokemonName,pokemonUrl,experience,heigth,hp,attack,defense,specialAttack,specialDefense,speed,pokemonWeight,primaryType,secondaryType,pokemonPrice,firstAbility,secondAbility,firstMove,secondMove,thirdMove,fourthMove) VALUES (51,'persian','https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/53.svg',154,10,65,70,60,65,65,115,320,'normal',NULL,24,'limber','technician','pay-day','scratch','cut','headbutt');


  


